sudo: required

language: go

services:
  - docker

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

jobs:
  include:
    - stage: check
      script: make check
    - stage: test
      script: make test-unit
    - stage: integration
      script: make test-integration
